spring:
  jpa:
    properties:
      hibernate:
        default_schema: public
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0816f8b9db1688
    password: a8c2bf2ed370ef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    test-connection: true

server:
  port: 8080