package org.youcode.mediconseil.domain.enums;

public enum Permission {
    // Permissions pour Patient
    USER_BOOK_APPOINTMENT,
    USER_VIEW_APPOINTMENT_DETAILS,
    USER_CANCEL_APPOINTMENT,
    USER_RESCHEDULE_APPOINTMENT,
    USER_VIEW_DOCTOR_PROFILES,
    USER_RECEIVE_CONSULTATION_DOCUMENT,
    USER_READ_HEALTH_ARTICLES,
    USER_MANAGE_PERSONAL_INFO,
    USER_VIEW_NOTIFICATIONS,
    USER_VIEW_CONSULTATION_HISTORY,

    // Permissions pour Doctor
    DOCTOR_VIEW_APPOINTMENTS,
    DOCTOR_CONFIRM_APPOINTMENT,
    DOCTOR_CANCEL_APPOINTMENT,
    DOCTOR_RESCHEDULE_APPOINTMENT,
    DOCTOR_VIEW_PATIENT_DETAILS,
    DOCTOR_PROVIDE_CONSULTATION_DOCUMENT,
    DOCTOR_MANAGE_HEALTH_ARTICLES,
    DOCTOR_MANAGE_AVAILABILITY,
    DOCTOR_VIEW_SCHEDULE,
    DOCTOR_MANAGE_PROFILE,
    DOCTOR_VIEW_STATISTICS,

    // Permissions pour Admin
    ADMIN_MANAGE_APPOINTMENTS,
    ADMIN_VIEW_APPOINTMENT_DETAILS,
    ADMIN_CANCEL_APPOINTMENT,
    ADMIN_RESCHEDULE_APPOINTMENT,
    ADMIN_VIEW_DOCTOR_SCHEDULES,
    ADMIN_MANAGE_DOCTOR_AVAILABILITY,
    ADMIN_MANAGE_HEALTH_ARTICLES,
    ADMIN_PUBLISH_HEALTH_ARTICLES,
    ADMIN_MANAGE_USERS,
    ADMIN_MANAGE_DOCTORS,
    ADMIN_VIEW_STATISTICS,
    ADMIN_MANAGE_NOTIFICATIONS
}